### ISSUE TITLE
Work out SQL commands to use for each endpoint's functionality

### ISSUE THREAD

**Issue by tbtommyb** [a-la-node/database-project#5]
We can use the elephantsql SQL browser (or psql) to test what commands bring back.

**Comment by Cleop** [comment]
Retrieve:
- [x]  All reviews     (for /reviews/recent endpoint)
- [x]  All resources (for resources/reviewed)
- [x]  A user's reviews (/reviews?user_id)
- [x]  A full resource with reviews (/reviews?resource_id)
- [x]  the resource page and full review for a given review (when clicked on from the recent reviews on the landing page) (/reviews/{review_id}

Make:
- [x]  A user's login details with a post request (/login)
- [x]  A new review post (/reviews/{review_id}

**Comment by Cleop** [comment]
One pair can work on endpoints 3 and 6.
The other pair can work on endpoints 1,2,4,5 and 7.
